services:
  todo-backend:
    build:
      context: ./todo-springboot
    image: todo-springboot
    ports:
      - "9191:9191"
    depends_on:
      - mysql
      - todos-list
      - permify
    environment:
      PERMIFY_BASE_URL: http://permify:3476
      PERMIFY_TENANT_ID: t1
      TODOSLIST_BASE_URL: http://todos-list:8080

  todos-list:
    build:
      context: ./todos-list
    image: todos-list
    ports:
      - "8082:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/todo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: todo

  todo-flutter-web:
    build:
      context: ./todo_flutter
    image: todo-flutter-web
    ports:
      - "8081:80"
    depends_on:
      - todo-backend

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: todo
      MYSQL_DATABASE: todo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  prometheus:
    image: prom/prometheus
    container_name: prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

    depends_on:
      - todo-backend
  grafana:
    image: grafana/grafana
    container_name: grafana

    ports:
      - "3000:3000"

    depends_on:
      - prometheus

  permify:
    image: ghcr.io/permify/permify
    ports:
      - "3476:3476"
      - "3478:3478"
volumes:
  mysql_data:

