apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: todo-backend-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todo-backend
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: todo-backend
        controlledResources: ["cpu", "memory"]
        minAllowed:
          cpu: 100m
          memory: 256Mi
        maxAllowed:
          cpu: "1"
          memory: 1Gi
