spring.application.name=todos-list
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/todo}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:todo}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://hydra:4444/.well-known/jwks.json
